### ISSUE TITLE
STS endpoint requirements

### ISSUE THREAD

**Issue by ddemo-miriade** [awsdocs/aws-control-tower-guide#12]
Hi, last week I tried to activate Control Tower on an existing organization.
I followed all the checks in the prerequisites list, but 10 minutes after the configuration procedure start I got an error regarding STS endpoint activation for specific regions.
I suggest to add this requirement in the prerequisites checklist, because I didn't find any articles about this requirement,  just to avoid this annoying issue.

Regard, Daniele

**Comment by lundql** [comment]
Thank you for your feedback. This requirement is not in the prerequisites list because it is not an automated pre-check. It is listed in best practices for administrative setup. It is a requirement for any setup of AWS Control Tower, not just with an existing organization. I will look into where else we might be able to put this information. Thanks again!
