### ISSUE TITLE
AWSControlTowerExecutionRole StackSet

### ISSUE THREAD

**Issue by stefanolczak** [awsdocs/aws-control-tower-guide#33]
After enabling Control Tower it appears that StackSet "AWSControlTowerExecutionRole" is created and it is used to deploy AWSControlTowerExecutionRole to child accounts but I can't see that it's mentioned anywhere in the documentation. Can you please add it to the documentation? I'm not sure if its something new in 2.8 version of Control Tower.

**Comment by lundql** [comment]
Thank you for this feedback. Checking with the team.

**Comment by lundql** [comment]
@stefanolczak I believe this role and behavior is documented here, it is not new:
https://docs.aws.amazon.com/controltower/latest/userguide/roles-how.html#roles-and-accont-creation

**Comment by stefanolczak** [comment]
@lundql the page you are referencing documents the IAM role but not the StackSet I'm talking about.

I launched my landing zone in January using version 2.7 of Control Tower. My provisioned accounts had new resources created according to it:  https://docs.aws.amazon.com/controltower/latest/userguide/account-factory-considerations.html. I can see that the IAM Role **AWSControlTowerExecution** was created then but it wasn't created as part of any CloudFormation stack.

I also enrolled existing accounts and to achieve that there was a need to create the IAM role **AWSControlTowerExecution** manually ( https://docs.aws.amazon.com/controltower/latest/userguide/enroll-manually.html )

In February I decided to update my landing zone to version 2.8 and then I noticed that new StackSet **AWSControlTowerExecutionRole** is created on my management account. The StackSet tries to deploy the IAM Role **AWSControlTowerExecution** to member accounts from Cloudformation stack **StackSet-AWSControlTowerExecutionRole**. It fails because the role is already created. So I started to search the documentation for information about the new StackSet and I didn't find any. The stack **StackSet-AWSControlTowerExecutionRole** isn't documented here: https://docs.aws.amazon.com/controltower/latest/userguide/account-factory-considerations.html but it is created in 2.8.

I believe the issue is still valid and it's related to changes introduced in 2.8 which unfortunately aren't mentioned in the release notes and the documentation. Please review the issue again.

**Comment by lundql** [comment]
Hello, @stefanolczak 
Here's an update about this issue:
1. I am adding documentation of the stackset under the table of resources for the management account. I didn't get a clear answer about whether it is new, but it is clearly undocumented.
2. The error message is expected behavior and I am adding a note to make that more clear for readers. Here's a quote from the SDE: "So the Stack instance fails if an account already has a role. This is expected"

That's what I know right now and what I am doing right now.

**Comment by lundql** [comment]
Explanation: My understanding so far is that the error was not caused specifically because you were updating to 2.8, but that you were updating _at all_, and so the role existed from when the accounts were previously created, updated with re-register, or manually enrolled. The AWSControlTowerExecution IAM role would already have to be in each account. All that the StackSet instance does is try to create the role, and so it fails because the role exists. Probably we need a better way to handle that in terms of an error message. I could be wrong, but that's how it seems after the research I have been doing.

**Comment by lundql** [comment]
P.S. As I understand it, the stack set is not documented in the page you linked, here: https://docs.aws.amazon.com/controltower/latest/userguide/account-factory-considerations.html

Because it should be documented in resources under the management account, in the table for the management account:
https://docs.aws.amazon.com/controltower/latest/userguide/how-control-tower-works.html#what-shared

That's because, as I understand from SMEs, the instance is not created by Account Factory in the vended account, but the stack set instance exists in the management account. Again, I could be wrong but that is what I have been looking into so far.
